### PR TITLE
some better mac instructions

### PR DESCRIPTION
**Pull request by jesscold**
also added some idiot proofing to both docs and app.

By the way, `dev-start.sh` for mac is wrong, but my bash-foo is not strong enough to fix it.

```bash
sh yarn dev
sh yarn dev-gui
```

The first command never finishes, so the 2nd one never runs.

### CODE REVIEW

**Comment by wisp101** [comment]
Couldn't `dev-start.sh` be fixed by writing `yarn dev & yarn dev-gui`?

**Comment by jesscold** [comment]
Yes, but that backgrounds the dev process, so when you stop the gui it continues to run and you have to pkill it. 

I would rather run them in separate terminals then have to deal with that. 
Also noobs will never even know what happened.

The question I have is why cant dev-gui also run whatever `yarn dev` runs / do hot reloading ?

**Comment by wisp101** [comment]
Well all `dev-gui` does is start electron. `dev` runs the nuxt dev server. You can't make one command do both at once since both run in the foreground.

I think switching the order of commands would fix the problem of manually killing the daemonzied process since a user could just kill the electron process without the command line.

Also I just realized your targeting the master branch. You should try targeting canary.

**Comment by kolessios** [comment]
I implement most of your changes manually since the PR was done before v1.0.0. Thank you!

**Pull request closed without merging**
